name: Run Yandex Disk Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run disk monitor
        run: |
          python disk_folder_monitor_once.py
        env:
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          FOLDER_PATH: ${{ secrets.FOLDER_PATH }}

      - name: Commit state
        run: |
          git fetch origin
          git checkout -B data origin/data || git checkout -b data
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Добавляем только те файлы, которые существуют
          test -f previous_state.json && git add previous_state.json
          test -f notified_etags.json && git add notified_etags.json
          test -f notified_mods.json && git add notified_mods.json

          git diff --cached --quiet || git commit -m "Update state [bot]"
          git push --force origin data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
