name: Run Yandex Disk Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Каждые 1 час
  workflow_dispatch:     # Возможность ручного запуска

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run disk monitor
        run: |
          python disk_folder_monitor_once.py
