name: Run Yandex Disk Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 15 минут
  workflow_dispatch:     # Возможность ручного запуска

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests
      - name: Cache state files
        uses: actions/cache@v3
        with:
          path: |
            previous_state.json
            notified_etags.json
          key: ${{ runner.os }}-yadisk-state
      - name: Run disk monitor
        run: python disk_folder_monitor_once.py
        env:
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          FOLDER_PATH: ${{ secrets.FOLDER_PATH }}
