name: Run Yandex Disk Monitors

on:
  schedule:
    - cron: '*/15 * * * *'  # Каждые 15 минут по UTC
  workflow_dispatch:

jobs:
  run-monitors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run etag-based monitor (file content changes)
        run: python disk_folder_monitor_once.py
        env:
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          FOLDER_PATH: ${{ secrets.FOLDER_PATH }}

      - name: Run journal-based monitor (file/folder actions)
        run: python journal_monitor.py
        env:
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          FOLDER_PATH: ${{ secrets.FOLDER_PATH }}
